#!/usr/bin/env bash
# =============================================================================
# T-Mobile Throttle Defeat — Setup Script
# Configures a Raspberry Pi as a TTL-rewriting NAT gateway to defeat
# T-Mobile hotspot throttling detection.
#
# Compatible with: Raspberry Pi OS Bookworm/Bullseye/Buster (and Stretch/Jessie)
# Run as root: sudo ./setup.sh
#
# Before running, see Step 0 in README.md to identify your interface names:
#   ip -br addr show
#   ip route show
# =============================================================================

set -euo pipefail

# =============================================================================
# CONFIGURATION — edit these values for your setup
# =============================================================================

# Interface connected to the T-Mobile modem/hotspot (upstream/WAN side)
# Examples: wlan0 (WiFi hotspot), eth0 (Ethernet LTE modem), usb0 (USB tether)
WAN_IFACE="wlan0"

# Interface connected to your home router's WAN port (downstream/LAN side)
# Examples: eth0 (built-in Ethernet), eth1 (USB-to-Ethernet adapter)
LAN_IFACE="eth0"

# Static IP for this Pi on the LAN side
LAN_IP="192.168.6.1"
LAN_NETMASK="255.255.255.0"
LAN_SUBNET="192.168.6.0"
LAN_BROADCAST="192.168.6.255"

# DHCP range handed out to devices behind the Pi
DHCP_START="192.168.6.50"
DHCP_END="192.168.6.150"
DHCP_LEASE="12h"

# Upstream DNS server
# 1.1.1.1 = Cloudflare, 8.8.8.8 = Google, 9.9.9.9 = Quad9
DNS_SERVER="1.1.1.1"

# TTL to force on all outgoing packets — do not change
# Phone TTL is 64; we set 65 so after the phone decrements it, it reads as 64
TTL_VALUE=65

# =============================================================================
# END CONFIGURATION
# =============================================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && die "Run as root: sudo $0"

# Validate interfaces exist before touching anything
ip link show "$WAN_IFACE" &>/dev/null || die "WAN interface '$WAN_IFACE' not found. Run: ip -br addr show"
ip link show "$LAN_IFACE" &>/dev/null || die "LAN interface '$LAN_IFACE' not found. Run: ip -br addr show"

info "Configuration:"
echo "  WAN (modem side) : $WAN_IFACE"
echo "  LAN (router side): $LAN_IFACE"
echo "  Pi LAN IP        : $LAN_IP"
echo "  DHCP range       : $DHCP_START – $DHCP_END"
echo "  DNS              : $DNS_SERVER"
echo "  TTL override     : $TTL_VALUE"
echo ""

# -----------------------------------------------------------------------------
# 1. Install dependencies
# -----------------------------------------------------------------------------
info "Installing packages..."
apt-get update -qq
apt-get install -y dnsmasq netfilter-persistent iptables-persistent

# -----------------------------------------------------------------------------
# 2. Static IP on LAN interface
# Pi OS Bookworm/Bullseye uses dhcpcd; older releases use /etc/network/interfaces
# -----------------------------------------------------------------------------
info "Configuring static IP on $LAN_IFACE..."

DHCPCD_CONF="/etc/dhcpcd.conf"
if [[ -f "$DHCPCD_CONF" ]]; then
    # Remove any existing static config block for this interface
    sed -i "/^interface ${LAN_IFACE}/,/^$/d" "$DHCPCD_CONF"
    cat >> "$DHCPCD_CONF" <<EOF

interface ${LAN_IFACE}
    static ip_address=${LAN_IP}/24
    nohook wpa_supplicant
EOF
    info "Written static config to $DHCPCD_CONF"
else
    warn "dhcpcd.conf not found — falling back to /etc/network/interfaces (Jessie/Stretch)"
    IFACES="/etc/network/interfaces"
    sed -i "/^allow-hotplug ${LAN_IFACE}/,/^$/d" "$IFACES"
    sed -i "/^iface ${LAN_IFACE}/,/^$/d" "$IFACES"
    cat >> "$IFACES" <<EOF

allow-hotplug ${LAN_IFACE}
iface ${LAN_IFACE} inet static
  address ${LAN_IP}
  netmask ${LAN_NETMASK}
  network ${LAN_SUBNET}
  broadcast ${LAN_BROADCAST}
EOF
    info "Written static config to $IFACES"
fi

# -----------------------------------------------------------------------------
# 3. Enable IPv4 forwarding
# -----------------------------------------------------------------------------
info "Enabling IPv4 forwarding..."
sed -i 's/^#\?net\.ipv4\.ip_forward=.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=1

# -----------------------------------------------------------------------------
# 4. Configure dnsmasq
# -----------------------------------------------------------------------------
info "Configuring dnsmasq..."
[[ -f /etc/dnsmasq.conf ]] && cp /etc/dnsmasq.conf /etc/dnsmasq.conf.orig

cat > /etc/dnsmasq.conf <<EOF
# T-Mobile throttle defeat — generated by setup.sh on $(date)

interface=${LAN_IFACE}
listen-address=${LAN_IP}
bind-interfaces
server=${DNS_SERVER}
domain-needed
bogus-priv
dhcp-range=${DHCP_START},${DHCP_END},${DHCP_LEASE}
EOF

systemctl enable dnsmasq
systemctl restart dnsmasq
info "dnsmasq configured and restarted"

# -----------------------------------------------------------------------------
# 5. iptables — NAT masquerade + TTL override
# Detects whether to use iptables-legacy (nftables backend) or iptables
# -----------------------------------------------------------------------------
info "Configuring iptables rules..."

if command -v iptables-legacy &>/dev/null; then
    IPT="iptables-legacy"
    warn "Using iptables-legacy (nftables backend detected on this OS)"
else
    IPT="iptables"
fi

# Remove existing rules to avoid duplicates on re-run
$IPT -t nat    -D POSTROUTING -o "$WAN_IFACE" -j MASQUERADE         2>/dev/null || true
$IPT -t mangle -D POSTROUTING -j TTL --ttl-set "$TTL_VALUE"          2>/dev/null || true

# Add rules
$IPT -t nat    -A POSTROUTING -o "$WAN_IFACE" -j MASQUERADE
$IPT -t mangle -A POSTROUTING -j TTL --ttl-set "$TTL_VALUE"

# Persist across reboots
netfilter-persistent save
systemctl enable netfilter-persistent
info "iptables rules saved"

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
echo ""
info "Setup complete. Reboot to verify everything comes up cleanly:"
echo "  sudo reboot"
echo ""
echo "After reboot, plug an Ethernet cable from this Pi into your router's WAN port."
echo ""
echo "Verify TTL is being overwritten:"
echo "  sudo tcpdump -i ${WAN_IFACE} -n 'icmp' -v | grep ttl"
